services:
  # ================================
  # BASE DE DATOS POSTGRESQL (COMENTADO - USANDO PostgreSQL LOCAL)
  # ================================
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: staycumbrecita-postgres-dev
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # ================================
  # BACKEND NESTJS (DESARROLLO)
  # ================================
  backend:
    build:
      context: ./backendStayCumbrecita
      dockerfile: Dockerfile
      target: builder
    container_name: staycumbrecita-backend-dev
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - ./backendStayCumbrecita/.env
    environment:
      # Base de datos para Docker - Conectar a PostgreSQL local
      DB_HOST: host.docker.internal
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      
      # Configuración de desarrollo
      NODE_ENV: development
      PORT: 5001
      HOST: 0.0.0.0
      
      # Encriptación y seguridad
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      ENCRYPTION_IV: ${ENCRYPTION_IV}
      SALT_ROUNDS: ${SALT_ROUNDS}
      SECRET_PEPPER: ${SECRET_PEPPER}
      
      # Cloudinary
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      
      # Gmail
      GMAIL_HOST: ${GMAIL_HOST}
      GMAIL_PORT: ${GMAIL_PORT}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_PASS: ${GMAIL_PASS}
      GMAIL_SECURE: ${GMAIL_SECURE}
      GMAIL_FROM: ${GMAIL_FROM}
      
      # URLs para Docker
      APP_NAME: ${APP_NAME}
      APP_BACKEND_URL: http://backend:5001
      APP_FRONTEND_URL: http://localhost:3000
    volumes:
      - ./backendStayCumbrecita:/app
      - /app/node_modules
      - backend_uploads:/app/uploads
    depends_on: []
    networks:
      - app-network
    command: npm run start:dev

  # ================================
  # FRONTEND NEXTJS (DESARROLLO)
  # ================================
  frontend:
    build:
      context: ./frontendStayCumbrecita
      dockerfile: Dockerfile
      target: builder
    container_name: staycumbrecita-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontendStayCumbrecita/.env.local
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5001
      NEXT_PUBLIC_FRONTEND_URL: http://localhost:3000
      NEXT_TELEMETRY_DISABLED: 1
      
      # URL interna para SSR (comunicación entre contenedores)
      INTERNAL_API_URL: http://backend:5001
      
      # Google Maps API Key
      NEXT_PUBLIC_MAPS_API_GOOGLE_KEY: ${NEXT_PUBLIC_MAPS_API_GOOGLE_KEY}
    volumes:
      - ./frontendStayCumbrecita:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network
    command: npm run dev

  # ================================
  # REDIS (DESARROLLO)
  # ================================
  redis:
    image: redis:7-alpine
    container_name: staycumbrecita-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

# ================================
# VOLUMES
# ================================
volumes:
  # postgres_dev_data:
  #   driver: local
  backend_uploads:
    driver: local

# ================================
# NETWORKS
# ================================
networks:
  app-network:
    driver: bridge 