export enum EstadoReserva {
  CREADA = 'CREADA',
  PENDIENTE_PAGO = 'PENDIENTE_PAGO',
  PAGADA = 'PAGADA',
  CONFIRMADA = 'CONFIRMADA',
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  CERRADA = 'CERRADA',
  CANCELADA = 'CANCELADA'
} 