export enum TipoAjustePrecio {
  TEMPORADA_ALTA = 'TEMPORADA_ALTA',
  TEMPORADA_BAJA = 'TEMPORADA_BAJA',
  FIN_DE_SEMANA = 'FIN_DE_SEMANA',
  FIN_DE_SEMANA_LARGO = 'FIN_DE_SEMANA_LARGO',
  EVENTO = 'EVENTO'
} 